// ==========================================================
// src/components/modals/TermsOfUseModal.tsx
// Terms of Use Popup Dialog
// ==========================================================

import React from 'react';
import { FileText, Check, AlertTriangle, Copyright, Scale, GraduationCap } from 'lucide-react';
import { BaseModal } from './BaseModal';
import { useLanguage } from '../../context/LanguageContext';

interface TermsOfUseModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export function TermsOfUseModal({ isOpen, onClose }: TermsOfUseModalProps) {
  const { isArabic } = useLanguage();

  return (
    <BaseModal
      isOpen={isOpen}
      onClose={onClose}
      title={isArabic ? 'شروط وسياسة الاستخدام' : 'Terms of Use & Guidelines'}
      subtitle={isArabic ? 'القواعد والإرشادات المنظمة لاستخدام منصة الأوامر' : 'Rules and guidelines for using the Prompt Studio'}
      icon={FileText}
      iconColor="bg-indigo-500/10 text-indigo-500"
      maxWidth="3xl"
    >
      <div className="space-y-6 text-sm text-foreground/90 leading-relaxed">
        {/* Intro */}
        <p className="text-xs sm:text-sm text-muted-foreground">
          {isArabic
            ? 'مرحباً بك في مختبر أوامر الذكاء الاصطناعي. باستخدامك للمنصة، فإنك توافق على الالتزام ببنود الاستخدام التالية المصممة لضمان بيئة آمنة، تعليمية، وبناءة لجميع المستخدمين.'
            : 'Welcome to the Interactive AI Prompt Studio. By accessing or using this platform, you agree to comply with the following terms designed to foster a safe, educational, and productive environment.'}
        </p>

        {/* Term 1: Permitted Use */}
        <div className="space-y-2">
          <div className="flex items-center gap-2 text-foreground font-bold">
            <GraduationCap className="w-4 h-4 text-blue-500" />
            <h4>{isArabic ? '1. الاستخدام المسموح والمجاني' : '1. Permitted & Educational Use'}</h4>
          </div>
          <p className="text-xs sm:text-sm text-muted-foreground">
            {isArabic
              ? 'تُقدَّم المنصة مجاناً للأغراض التعليمية، البحثية، والمهنية. يحق لك نسخ، وتعديل، وتخصيص، وتطبيق قوالب الأوامر والجرائد المدرسية والإنفوجرافيك لأعمالك ودروسك دون قيود تجارية على مخرجاتك الخاصة.'
              : 'The platform is provided free of charge for educational, research, and professional purposes. You are fully permitted to copy, tweak, adapt, and deploy our prompt templates, educational newspapers, and infographics in your own classrooms, projects, and products.'}
          </p>
        </div>

        {/* Term 2: Intellectual Property */}
        <div className="space-y-2">
          <div className="flex items-center gap-2 text-foreground font-bold">
            <Copyright className="w-4 h-4 text-purple-500" />
            <h4>{isArabic ? '2. الملكية الفكرية للقوالب والمنصة' : '2. Intellectual Property & Templates'}</h4>
          </div>
          <p className="text-xs sm:text-sm text-muted-foreground">
            {isArabic
              ? 'تصميم المنصة، وهيكلية القوالب، والأكواد البرمجية الأصلية محمية بموجب حقوق التأليف والنشر. يُسمح لك بمشاركة روابط الأوامر والباقات المصدرة، بينما يُحظر استنساخ الواجهة بالكامل لإعادة بيعها بشكل مضلل.'
              : 'The platform architecture, UI components, and curated core library frameworks are protected by copyright. You are welcome to share exported prompt packs and workflow links, while misleading duplication or commercial repackaging of the entire platform interface is prohibited.'}
          </p>
        </div>

        {/* Term 3: AI Disclaimer */}
        <div className="space-y-2 p-3.5 rounded-xl bg-amber-500/5 border border-amber-500/20">
          <div className="flex items-center gap-2 text-amber-700 dark:text-amber-300 font-bold">
            <AlertTriangle className="w-4 h-4 text-amber-500" />
            <h4>{isArabic ? '3. إخلاء المسؤولية عن مخرجات الذكاء الاصطناعي' : '3. AI Output Disclaimer'}</h4>
          </div>
          <p className="text-xs sm:text-sm text-muted-foreground mt-1">
            {isArabic
              ? 'أوامر الذكاء الاصطناعي هي أدوات مساعدة لتحسين جودة واستجابة نماذج اللغة (LLMs). تقع على عاتق المستخدم مسؤولية مراجعة والتحقق من صحة ودقة أي محتوى علمي أو قانوني أو طبي مولد بواسطة نماذج الذكاء الاصطناعي قبل اعتماده.'
              : 'AI prompts serve as structured directives to guide large language models (LLMs). Users remain solely responsible for reviewing and verifying the factual, scientific, and legal accuracy of any outputs generated by AI models before publication.'}
          </p>
        </div>

        {/* Term 4: Compliance */}
        <div className="space-y-2">
          <div className="flex items-center gap-2 text-foreground font-bold">
            <Scale className="w-4 h-4 text-emerald-500" />
            <h4>{isArabic ? '4. الالتزام بالاستخدام الأخلاقي' : '4. Ethical & Responsible AI Usage'}</h4>
          </div>
          <p className="text-xs sm:text-sm text-muted-foreground">
            {isArabic
              ? 'يلتزم المستخدم بعدم استغلال المنصة أو قوالبها لتوليد محتوى ضار، أو احتيالي، أو ينتهك القوانين والأنظمة المعمول بها أو خصوصية الآخرين.'
              : 'Users agree not to utilize the platform or its templates to generate harmful, fraudulent, deceptive, or rights-infringing content in violation of applicable laws and ethical AI standards.'}
          </p>
        </div>

        {/* Timestamp */}
        <div className="pt-2 text-[11px] text-muted-foreground text-end border-t border-border/50 font-mono">
          {isArabic ? 'تاريخ السريان: سبتمبر 2026' : 'Effective Date: September 2026'}
        </div>
      </div>
    </BaseModal>
  );
}
